@startuml Diagrama de classe universidade
scale 2
left to right direction 

skinparam ClassAttributeIconSize 0
class Usuario{
    -String login
    -String senha
}

class Secretario{
    -Secretario List<secretarios>
    +void addToList(Secretario secretario)
    +void gerarCurriculo()
}


class Professor{
    -Professor List<professores>
    +void consultarMatriculas(Turma turma)
}

class Aluno{
    -String[4] disciplinas
    -Diciplina List<diciplinas>
    +void matricularEmDisciplina(Disciplina disciplina)
    +void cancelarMatriculaDisciplina(Disciplina disciplina)
    +void pagarDisciplina(Disciplina disciplina)
}

class Curso{
    -String nome
    -Int creditos
    -String[] disciplinasIds
}

class Disciplina{
    -String nome
    -Boolean ativa
    -Boolean isMatriculasAbertas
    -Disciplina List<disciplinas>
}

class Turma{
    -String name
    -String[1000] alunosIds
    -String professorId
    -String dusciplinaId
    -Turma List<turmas>
}

Usuario <|-- Secretario

Usuario <|-- Professor

Usuario <|-- Aluno

Curso *-- Disciplina

Turma *-- Disciplina

Turma *-- Professor

Turma *-- Aluno

Professor <-- Turma

Aluno o-- Disciplina

@enduml