@startuml Diagrama de caso Universidade
scale 2
left to right direction 
actor Secretaria
actor Professor
actor Aluno

usecase (Notificar sistema de pagamento) as nsp
usecase (Gerar curriculo) as gc
usecase (Gerenciar informacoes) as gi
usecase (Matricular em disciplinas) as med
usecase (Cancelar matriculas) as canm
usecase (Consultar matriculas) as conm

Secretaria -- gc
Secretaria -- gi

Aluno -- med
Aluno -- canm

Professor -- conm
Aluno -- conm

canm<.nsp : include
med<.nsp : include


@enduml